version: '3'

services:
  nomad:
    image: multani/nomad
    command: agent -dev -config=/etc/nomad/local.conf
    privileged: true
    network_mode: host
    environment:
      NOMAD_LOCAL_CONFIG: |
        data_dir = "/nomad/data/"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp:/tmp
      - ./nomad:/etc/nomad/
  
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: inferrd
      POSTGRES_USER: inferrd
      POSTGRES_DB: inferrd

  redis:
    image: redis
    restart: always

  elastic:
    image: elasticsearch:8.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    restart: always

  fluent:
    image: fluent/fluentd
    command: sh ./local/entrypoint.sh
    ports:
      - "24224:24224"
    restart: always
    volumes:
      - ./fluentd:/etc/fluent/

  api:
    build: .
    command: yarn run start
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - fluent
      - nomad
      - elastic
    environment:
      - DATABASE_URL=postgres://inferrd:inferrd@db:5432/inferrd
      - REDIS_URL=redis://redis:6379/0
      - NOMAD_ADDR=http://nomad:4646
      - DEBUG=inferrd/*
      - NODE_ENV=docker
      - APP_HOST=http://localhost:3001
      - API_HOST=http://localhost:3000
      - DOCKER_HOST=http://api:3000
      - LOGS_ES=https://elastic:9200

  ui:
    build: ./ui
    ports:
      - "3001:3001"
    depends_on:
      - api