name: TensorFlow Runtime Docker Image

on:
  push:
    branches: [ "main" ]
    paths: [ "runtimes/tensorflow/**/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd runtimes/tensorflow && docker build . --file Dockerfile --tag inferrd/tensorflow:latest
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push to Docker Registry
      run: docker push inferrd/tensorflow:latest
